# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Steph/Documents/Dev/Verilog/BPSK/xdc/cmod35t reciever.xdc

# IP: C:/Users/Steph/Documents/Dev/Verilog/BPSK/src/ip/MMCM/MMCM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MMCM || ORIG_REF_NAME==MMCM} -quiet] -quiet

# IP: C:/Users/Steph/Documents/Dev/Verilog/BPSK/src/ip/demod_mult/demod_mult.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demod_mult || ORIG_REF_NAME==demod_mult} -quiet] -quiet
